name: Publish images

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Checkout repo, grab QBT version
        id: getVersion
        run: echo "QBT_VERSION=$(grep -o -m 1 'QBT_VERSION=.*' Dockerfile | awk -F '-' '{print $2}')" >> $GITHUB_ENV
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            fthffs/qbittorrent:latest
            fthffs/qbittorrent:${{ env.QBT_VERSION }}
            ghcr.io/fthffs/qbittorrent:latest
            ghcr.io/fthffs/qbittorrent:${{ env.QBT_VERSION }}
